server:
  port: 8080

spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:order-service
    driverClassName: org.h2.Driver
    username: sa
    password: admin
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    show-sql: true
  jackson:
    serialization:
      fail-on-empty-beans: false
  rabbitmq:
    username: admin
    password: admin

rabbit:
  exchange: orchestration-exchange
  routing-key: order-created