server:
  port: 8082

spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:payment-service
    driverClassName: org.h2.Driver
    username: sa
    password: admin
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  jackson:
    serialization:
      fail-on-empty-beans: false
